version: 0.2
env:
  NOMBRE_LAMBDA: "prueba"
  CAPA_PD_YF: "capa_pd_yf"
  LAYER_PREFIX: "arn:aws:lambda:us-east-1:891377103104:layer"
phases:
  install:
    runtime-versions:
      python: 3.13  
    commands:
      - echo "Instalación de dependencias"
      - mkdir -p python
      - pip install -r requirements.txt -t python --no-cache-dir
  build:
    commands:
      - echo "Paquetes con dependencias y código"
      - zip -r9 dependencies_layer.zip python -x "*/__pycache__/*" "*.dist-info/*" "*.egg-info/*" || exit 1
      - zip -r9 deployment_package.zip lambda_function.py || exit 1
      - du -sh dependencies_layer.zip
  post_build:
    commands:
      - |
        if ! aws lambda get-function --function-name $NOMBRE_LAMBDA >/dev/null 2>&1; then
          -- echo "Creando Lambda..."
          -- aws lambda create-function --function-name $NOMBRE_LAMBDA --runtime python3.13 --role FIXME --handler lambda_function.lambda_handler
        else
          -- echo "La Lambda ya existe"
        fi
      - echo "Actualizar capa de la Lambda"
      - aws lambda publish-layer-version --layer-name $CAPA_PD_YF --zip-file fileb://dependencies_layer.zip --compatible-runtimes python3.13 || exit 1
      - echo "Número de la última versión"
      - LAYER_VERSION=$(aws lambda list-layer-versions --layer-name dependencias --query 'LayerVersions[0].Version' --output text)
      - echo "Actualizar con código y dependencias nuevas"
      - aws lambda update-function-code --function-name $NOMBRE_LAMBDA --zip-file fileb://deployment_package.zip || exit 1
      - aws lambda wait function-updated --function-name $NOMBRE_LAMBDA
      - aws lambda update-function-configuration --function-name $NOMBRE_LAMBDA --layers $LAYER_PREFIX:$CAPA_PD_YF:$LAYER_VERSION || exit 1
      
      - echo "Finalizado"
