version: 0.2
env:
  variables:
    LAMBDA_LAYER_NAME: "prueba-dependencies"  # Name of the Lambda layer
phases:
  install:
    runtime-versions:
      python: 3.13  # Retain Python 3.13 as supported by AWS
    commands:
      - echo "Installing dependencies..."
      - mkdir -p python  # Prepare folder for Lambda layer
      - pip install -r requirements.txt -t python
  build:
    commands:
      - echo "Creating Lambda layer package..."
      - zip -r9 dependencies_layer.zip python || exit 1
      - echo "Creating deployment package..."
      - zip -r9 deployment_package.zip lambda_function.py || exit 1
  post_build:
    commands:
      - echo "Uploading Lambda layer..."
      - aws lambda publish-layer-version --layer-name prueba-dependencies --zip-file fileb://dependencies_layer.zip --compatible-runtimes python3.13 || exit 1
      - echo "Getting latest layer version..."
      - LAYER_VERSION=$(aws lambda list-layer-versions --layer-name prueba-dependencies --query 'LayerVersions[0].Version' --output text)
      - echo "Updating Lambda function with the new deployment package and layer..."
      - aws lambda update-function-code --function-name prueba --zip-file fileb://deployment_package.zip || exit 1
      - aws lambda update-function-configuration --function-name prueba --layers arn:aws:lambda:$AWS_REGION:$AWS_ACCOUNT_ID:layer:prueba-dependencies:$LAYER_VERSION || exit 1
      - echo "Deployment complete!"
