version: 0.2
env:
  variables:
    NOMBRE_LAMBDA: "prueba2"
    CAPA_PD_YF: "capa_pd_yf"
    LAYER_PREFIX: "arn:aws:lambda:us-east-1:891377103104:layer"
    REGION: "us-east-1"
    COD_USER: "891377103104"
    ROL_LAMBDA_NAME: "rol_lambda"
    NOMBRE_BUCKET: "almacenamiento-primario"
phases:
  install:
    runtime-versions:
      python: 3.13  
    commands:
      - echo "Instalación de dependencias"
      - mkdir -p python
      - pip install -r requirements.txt -t python --no-cache-dir
  build:
    commands:
      - echo "Paquetes con dependencias y código"
      - zip -r9 dependencies_layer.zip python -x "*/__pycache__/*" "*.dist-info/*" "*.egg-info/*" || exit 1
      - zip -r9 deployment_package.zip lambda_function.py || exit 1
      - du -sh dependencies_layer.zip
  post_build:
    commands:
      - echo "Crear S3 si no existe"
      - |
        if ! aws s3api head-bucket --bucket $NOMBRE_BUCKET >/dev/null 2>&1; then
          echo "Bucket S3 no existe, creando";
          aws s3api create-bucket --bucket $NOMBRE_BUCKET --region $REGION
        else
          echo "Bucket S3 ya existe"
        fi

      - echo "Crear roles si no existen"
      - |
        if ! aws iam get-role --role-name $ROL_LAMBDA_NAME >/dev/null 2>&1; then
          echo "Rol no existe, creando"
          aws iam create-role --role-name $ROL_LAMBDA_NAME --assume-role-policy-document file://trust-politica.json;
          aws iam put-role-policy --role-name $ROL_LAMBDA_NAME --policy-name S3AccesoCompleto --policy-document file://s3-politica.json;
          aws iam attach-role-policy --role-name $ROL_LAMBDA_NAME --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole;
        else
          echo "Rol ya existe"
        fi
        
      - echo "Crear la Lambda si no existe"
      - |
        if ! aws lambda get-function --function-name $NOMBRE_LAMBDA >/dev/null 2>&1; then
          echo "Función no existe, creando"
          aws lambda create-function --function-name $NOMBRE_LAMBDA --runtime python3.13 --role arn:aws:iam::$COD_USER:role/$ROL_LAMBDA_NAME --handler lambda_function.lambda_handler --zip-file fileb://deployment_package.zip --timeout 30 --memory-size 256
        else
          echo "Función ya creada"
        fi
        
      - echo "Actualizar capa de la Lambda"
      - aws lambda publish-layer-version --layer-name $CAPA_PD_YF --zip-file fileb://dependencies_layer.zip --compatible-runtimes python3.13 || exit 1
      
      - echo "Número de la última versión"
      - LAYER_VERSION=$(aws lambda list-layer-versions --layer-name $CAPA_PD_YF --query 'LayerVersions[0].Version' --output text)
      
      - echo "Actualizar con código y dependencias nuevas"
      - aws lambda update-function-code --function-name $NOMBRE_LAMBDA --zip-file fileb://deployment_package.zip || exit 1
      - aws lambda wait function-updated --function-name $NOMBRE_LAMBDA
      - aws lambda update-function-configuration --function-name $NOMBRE_LAMBDA --layers $LAYER_PREFIX:$CAPA_PD_YF:$LAYER_VERSION || exit 1
      
      - echo "Finalizado"
